"""Builders for realistic *synthetic* roast/cupping files.

There were no real Artisan/Cropster/cupping files available for this prototype, so
these produce plausible fixtures that the real parsers can round-trip. They are
clearly labelled synthetic. If real client files arrive, verify the parsers against
the actual bytes (PRD sections 0 and 8) -- field names in particular drift between
Artisan versions.

The same :func:`make_roast_curve` also feeds the bulk seed generator, so demo data
and parser fixtures share one physically-plausible curve model.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np


@dataclass
class CurveEvents:
    """Event times in seconds from CHARGE."""

    dry_end_time_s: float
    fc_start_time_s: float
    fc_end_time_s: float
    drop_time_s: float


def make_roast_curve(
    *,
    charge_temp: float = 204.0,
    tp_temp: float = 92.0,
    tp_time: float = 70.0,
    drop_temp: float = 210.0,
    drop_time: float = 590.0,
    dt: float = 2.0,
    rng: Optional[np.random.Generator] = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return ``(times, bt, et)`` from CHARGE (t=0) to DROP.

    BT falls linearly from ``charge_temp`` to the turning point, then rises with a
    decelerating slope (RoR high early, tapering) -- the classic roast shape. ET
    tracks a little above BT. Optional sensor noise via ``rng``.
    """
    times = np.arange(0.0, drop_time + dt, dt)
    bt = np.empty_like(times)
    for i, t in enumerate(times):
        if t <= tp_time:
            frac = t / tp_time if tp_time > 0 else 1.0
            bt[i] = charge_temp + (tp_temp - charge_temp) * frac
        else:
            x = (t - tp_time) / (drop_time - tp_time)
            bt[i] = tp_temp + (drop_temp - tp_temp) * (x ** 0.75)
    if rng is not None:
        bt = bt + rng.normal(0, 0.25, size=bt.shape)
    et = bt + 14.0 + (rng.normal(0, 0.4, size=bt.shape) if rng is not None else 0.0)
    return times, bt, et


def temp_at(times: np.ndarray, temps: np.ndarray, t: float) -> float:
    return float(np.interp(t, times, temps))


# --------------------------------------------------------------------------- #
# Artisan .alog  (Python dict literal, as Artisan writes it)
# --------------------------------------------------------------------------- #
def write_artisan_alog(
    path: str | Path,
    *,
    times: np.ndarray,
    bt: np.ndarray,
    et: np.ndarray,
    events: CurveEvents,
    lot_name: str,
    machine_id: str,
    roaster_name: str,
    roast_ref: str,
    roast_date: str,
    temp_unit: str = "C",
    pre_charge_s: float = 20.0,
    dt: float = 2.0,
) -> Path:
    """Write a synthetic Artisan profile. Includes a short pre-charge warmup so the
    CHARGE index is non-zero (unambiguous), mirroring a real recording."""
    n_pre = int(round(pre_charge_s / dt))
    pre_t = np.arange(0.0, pre_charge_s, dt)
    pre_bt = np.full(pre_t.shape, float(bt[0]))
    pre_et = np.full(pre_t.shape, float(et[0]))

    timex = np.concatenate([pre_t, times + pre_charge_s])
    temp2 = np.concatenate([pre_bt, bt])   # BT
    temp1 = np.concatenate([pre_et, et])   # ET

    def idx(t_from_charge: float) -> int:
        return int(round((t_from_charge + pre_charge_s) / dt))

    # timeindex = [CHARGE, DRYEND, FCstart, FCend, SCstart, SCend, DROP, COOL]
    timeindex = [
        n_pre,
        idx(events.dry_end_time_s),
        idx(events.fc_start_time_s),
        idx(events.fc_end_time_s),
        0,  # SC start (not reached)
        0,  # SC end
        idx(events.drop_time_s),
        0,  # cool (not recorded)
    ]

    profile = {
        "version": "2.8.10",
        "mode": temp_unit,
        "title": roast_ref,
        "beans": lot_name,
        "roastdate": roast_date,
        "roastertype": machine_id,
        "operator": roaster_name,
        "timex": [round(float(x), 1) for x in timex],
        "temp1": [round(float(x), 1) for x in temp1],
        "temp2": [round(float(x), 1) for x in temp2],
        "timeindex": timeindex,
        "_note": "SYNTHETIC fixture generated by GoodCup seed.synthetic_files",
    }
    path = Path(path)
    path.write_text(repr(profile), encoding="utf-8")
    return path


# --------------------------------------------------------------------------- #
# Cropster CSV  (metadata # lines + time series with an event column)
# --------------------------------------------------------------------------- #
def write_cropster_csv(
    path: str | Path,
    *,
    times: np.ndarray,
    bt: np.ndarray,
    et: np.ndarray,
    events: CurveEvents,
    lot_name: str,
    machine_id: str,
    roaster_name: str,
    roast_ref: str,
    roast_date: str,
    temp_unit: str = "C",
) -> Path:
    """Write a synthetic Cropster-style CSV. Time is seconds from CHARGE; event
    labels sit in an ``event`` column on the nearest sample row."""
    path = Path(path)
    event_at = {
        int(round(events.dry_end_time_s)): "Dry End",
        int(round(events.fc_start_time_s)): "First Crack",
        int(round(events.fc_end_time_s)): "First Crack End",
        int(round(events.drop_time_s)): "Drop",
    }
    with path.open("w", encoding="utf-8", newline="") as fh:
        fh.write("# Cropster Roast Export (SYNTHETIC)\n")
        fh.write(f"# Batch: {roast_ref}\n")
        fh.write(f"# Green: {lot_name}\n")
        fh.write(f"# Machine: {machine_id}\n")
        fh.write(f"# Roaster: {roaster_name}\n")
        fh.write(f"# Date: {roast_date}\n")
        fh.write(f"# Unit: {temp_unit}\n")
        writer = csv.writer(fh)
        writer.writerow(["time_s", "bean_temp", "env_temp", "event"])
        writer.writerow([0, round(float(bt[0]), 1), round(float(et[0]), 1), "Charge"])
        for t, b, e in zip(times, bt, et):
            ti = int(round(float(t)))
            if ti == 0:
                continue  # charge row already written
            writer.writerow([ti, round(float(b), 1), round(float(e), 1), event_at.get(ti, "")])
    return path


# --------------------------------------------------------------------------- #
# Cupping CSV  (matches templates/cupping_entry.csv)
# --------------------------------------------------------------------------- #
CUPPING_COLUMNS = [
    "roast_ref", "cupper_name", "cupping_date", "session_id", "form_type",
    "fragrance_aroma", "flavor", "aftertaste", "acidity", "body", "balance",
    "uniformity", "clean_cup", "sweetness", "overall", "defect_points",
    "total_score", "descriptors_raw", "notes",
]


def write_cupping_csv(path: str | Path, rows: list[dict]) -> Path:
    path = Path(path)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=CUPPING_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for r in rows:
            writer.writerow(r)
    return path


# --------------------------------------------------------------------------- #
# Repo fixtures + blank templates (deterministic)
# --------------------------------------------------------------------------- #
GREEN_TEMPLATE_COLUMNS = [
    "lot_name", "origin_country", "region", "farm_or_coop", "varietal", "process",
    "harvest_year", "altitude_masl", "density_g_per_l", "moisture_pct",
    "water_activity", "screen_size", "supplier", "arrival_date", "price_per_kg", "notes",
]
ROAST_TEMPLATE_COLUMNS = [
    "roast_ref", "lot_name", "machine_id", "roaster_name", "roast_date", "batch_size_g",
    "ambient_temp_c", "ambient_humidity_pct", "temp_unit", "charge_temp",
    "dry_end_time_s", "dry_end_temp", "fc_start_time_s", "fc_start_temp",
    "fc_end_time_s", "drop_time_s", "drop_temp", "source_software", "notes",
]


def _write_template(path: Path, columns: list[str], example: dict) -> None:
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerow({c: example.get(c, "") for c in columns})


def write_templates(templates_dir: str | Path) -> None:
    """Write blank CSV templates (header + one worked example row)."""
    d = Path(templates_dir)
    d.mkdir(parents=True, exist_ok=True)
    _write_template(d / "green_intake.csv", GREEN_TEMPLATE_COLUMNS, {
        "lot_name": "Kochere Washed", "origin_country": "Ethiopia", "region": "Yirgacheffe",
        "farm_or_coop": "Kochere Co-op", "varietal": "Heirloom", "process": "washed",
        "harvest_year": 2025, "altitude_masl": 1950, "density_g_per_l": 725,
        "moisture_pct": 10.4, "water_activity": 0.54, "screen_size": 15,
        "supplier": "Trabocca", "arrival_date": "2026-01-05", "price_per_kg": 8.4,
        "notes": "Bright, floral lot",
    })
    _write_template(d / "roast_manual.csv", ROAST_TEMPLATE_COLUMNS, {
        "roast_ref": "R-2026-014", "lot_name": "Kochere Washed", "machine_id": "Probat-P12",
        "roaster_name": "Sam", "roast_date": "2026-02-14", "batch_size_g": 1200,
        "ambient_temp_c": 27, "ambient_humidity_pct": 65, "temp_unit": "C",
        "charge_temp": 200, "dry_end_time_s": 300, "dry_end_temp": 150,
        "fc_start_time_s": 480, "fc_start_temp": 196, "fc_end_time_s": 540,
        "drop_time_s": 590, "drop_temp": 210, "source_software": "manual",
        "notes": "Paper-logged batch (no curve)",
    })
    _write_template(d / "cupping_entry.csv", CUPPING_COLUMNS, {
        "roast_ref": "R-2026-014", "cupper_name": "Ana", "cupping_date": "2026-02-17",
        "session_id": "SES-2026-05", "form_type": "sca_traditional",
        "fragrance_aroma": 8.0, "flavor": 8.25, "aftertaste": 7.75, "acidity": 8.25,
        "body": 7.5, "balance": 8.0, "uniformity": 10, "clean_cup": 10, "sweetness": 10,
        "overall": 8.0, "defect_points": 0, "total_score": 85.75,
        "descriptors_raw": "jasmine, bergamot, lemon, black tea",
        "notes": "Delicate, tea-like",
    })


def write_sample_fixtures(samples_dir: str | Path) -> dict:
    """Write the committed synthetic sample files used as parser fixtures.

    Deterministic (fixed RNG). Two Artisan profiles + one Cropster export, plus a
    cupping sheet scoring all three by two cuppers. Returns the paths written.
    """
    d = Path(samples_dir)
    d.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(7)

    specs = [
        dict(ref="R-2026-001", lot="Kochere Washed", machine="Probat-P12", roaster="Sam",
             date="2026-02-03", fmt="artisan",
             charge=204, tp_temp=91, tp_time=68, drop_temp=209, drop_time=588,
             dry_end=298, fc_start=474, fc_end=534),
        dict(ref="R-2026-002", lot="Sidama Natural", machine="Probat-P12", roaster="Mia",
             date="2026-02-04", fmt="artisan",
             charge=200, tp_temp=94, tp_time=74, drop_temp=213, drop_time=612,
             dry_end=320, fc_start=498, fc_end=560),
        dict(ref="R-2026-003", lot="Huila Pink Bourbon", machine="Loring-S15", roaster="Sam",
             date="2026-02-05", fmt="cropster",
             charge=198, tp_temp=90, tp_time=66, drop_temp=208, drop_time=602,
             dry_end=310, fc_start=486, fc_end=548),
    ]

    written = {"artisan": [], "cropster": [], "cupping": []}
    for s in specs:
        times, bt, et = make_roast_curve(
            charge_temp=s["charge"], tp_temp=s["tp_temp"], tp_time=s["tp_time"],
            drop_temp=s["drop_temp"], drop_time=s["drop_time"], dt=2.0, rng=rng,
        )
        events = CurveEvents(s["dry_end"], s["fc_start"], s["fc_end"], s["drop_time"])
        common = dict(
            times=times, bt=bt, et=et, events=events, lot_name=s["lot"],
            machine_id=s["machine"], roaster_name=s["roaster"], roast_ref=s["ref"],
            roast_date=s["date"], temp_unit="C",
        )
        if s["fmt"] == "artisan":
            p = write_artisan_alog(d / f"sample_artisan_{s['ref']}.alog", **common)
            written["artisan"].append(p)
        else:
            p = write_cropster_csv(d / f"sample_cropster_{s['ref']}.csv", **common)
            written["cropster"].append(p)

    # a cupping sheet: two cuppers score all three roasts (mixed nothing -- all SCA here)
    cup_rows = []
    base = {"R-2026-001": 86.0, "R-2026-002": 84.5, "R-2026-003": 85.25}
    descriptors = {
        "R-2026-001": "jasmine, bergamot, lemon, black tea, honey",
        "R-2026-002": "blueberry, strawberry, cocoa, winey",
        "R-2026-003": "red apple, caramel, orange, floral",
    }
    for ref, total in base.items():
        for cupper, delta in (("Ana", 0.0), ("Ben", -0.75)):
            cup_rows.append({
                "roast_ref": ref, "cupper_name": cupper, "cupping_date": "2026-02-10",
                "session_id": "SES-2026-02", "form_type": "sca_traditional",
                "fragrance_aroma": 7.75, "flavor": 8.0, "aftertaste": 7.5, "acidity": 8.0,
                "body": 7.5, "balance": 7.75, "uniformity": 10, "clean_cup": 10,
                "sweetness": 10, "overall": 7.75 + delta, "defect_points": 0,
                "total_score": round(total + delta, 2),
                "descriptors_raw": descriptors[ref], "notes": "",
            })
    p = write_cupping_csv(d / "sample_cupping_SES-2026-02.csv", cup_rows)
    written["cupping"].append(p)
    return written
